version: 2
updates:
  - package-ecosystem: docker
    directories:
      - /
      - /alpine
      - /debian
      - /ubuntu
      - /fedora
      - /rocky
      - /alma
      - /oracle
      - /amazon
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Santiago
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - docker
