stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

.build_base: &build_base
  stage: build
  image: docker:27-cli
  services:
    - name: docker:27-dind
      command: ["--mtu=1400"]

  before_script:
    - export BUILDER_NAME=builder-${CI_PIPELINE_ID}-${CI_JOB_ID}
    - docker buildx create --name $BUILDER_NAME --use --driver docker-container
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  after_script:
    - docker buildx rm $BUILDER_NAME --force || true
  script:
    - |
      case $VARIANT in
        release) BUILD_VARIANT=Release; SANITIZER=off;    SUFFIX="release" ;;
        debug)   BUILD_VARIANT=Debug;   SANITIZER=off;    SUFFIX="debug" ;;
        asan)    BUILD_VARIANT=Debug;   SANITIZER=asan;   SUFFIX="debug-asan" ;;
        tsan)    BUILD_VARIANT=Debug;   SANITIZER=tsan;   SUFFIX="debug-tsan" ;;
        ubsan)   BUILD_VARIANT=Debug;   SANITIZER=ubsan;  SUFFIX="debug-ubsan" ;;
      esac

      ARCH=$(echo "$PLATFORM" | cut -d/ -f2)
      BUILD_ARGS="--build-arg BUILD_VARIANT=$BUILD_VARIANT"
      if [ "$SANITIZER" != "off" ]; then
        BUILD_ARGS="$BUILD_ARGS --build-arg SANITIZER=$SANITIZER"
      fi

      TAGS=""

      if [ "$CI_COMMIT_BRANCH" = "master" ]; then
        TAGS="--tag $CI_REGISTRY_IMAGE:latest-${SUFFIX}-${DISTRO}-${ARCH}"
      fi

      if echo "$CI_COMMIT_TAG" | grep -q '^v'; then
        VERSION="${CI_COMMIT_TAG#v}"
        TAGS="$TAGS --tag $CI_REGISTRY_IMAGE:v${VERSION}-${SUFFIX}-${DISTRO}-${ARCH}"
      fi

      docker buildx build \
        --platform $PLATFORM \
        -f $DISTRO/Dockerfile \
        $BUILD_ARGS \
        $TAGS \
        --provenance=false \
        --push \
        .
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG =~ /^v.*/

build:amd64:
  <<: *build_base
  tags: [amd64]
  allow_failure: true
  parallel:
    matrix:
      - DISTRO: alpine
        VARIANT: [release, debug]
        PLATFORM: linux/amd64
      - DISTRO: [debian, ubuntu, fedora]
        VARIANT: [release, debug, asan, tsan, ubsan]
        PLATFORM: linux/amd64

build:arm64:
  <<: *build_base
  tags: [arm64]
  allow_failure: true
  parallel:
    matrix:
      - DISTRO: alpine
        VARIANT: [release, debug]
        PLATFORM: linux/arm64
      - DISTRO: [debian, ubuntu, fedora]
        VARIANT: [release, debug, asan, tsan, ubsan]
        PLATFORM: linux/arm64


